name: unit-test-actions
on: [push, pull_request]
jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      postgres: 
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Checkout to merge commit
        run: git checkout --progress --force ${{ github.sha }}

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: Setup database
        run: |
          psql -h localhost -U postgres -c 'CREATE DATABASE project;'
        env:
          PGPASSWORD: postgres

      - name: Test schema
        run: |
          psql -h localhost -U postgres -d project -f schema.sql
        env:
          PGPASSWORD: postgres

      - name: Test procedures
        run: |
          psql -h localhost -U postgres -d project -f proc.sql
        env:
          PGPASSWORD: postgres
                
      - name: Test triggers
        run: |
          psql -h localhost -U postgres -d project -f trigger.sql
        env:
          PGPASSWORD: postgres
